### PR TITLE
Evan Burrell - Add image. 

### PR DESCRIPTION
**Pull request by burrelle**
Added image. Removed lockfile that I accidentally committed.

### CODE REVIEW

**Comment by tnorthcutt** [comment]
@burrelle are you sure that added the image? I only see some css & js changes in your commit.

**Comment by burrelle** [comment]
Yeah it's there, it says binary file not shown...

**Comment by tnorthcutt** [comment]
@burrelle derp, my bad! Sorry for the interruption 😬

**Comment by burrelle** [comment]
All good, thanks for double checking @tnorthcutt

**Comment by mattstauffer** [comment]
Sorry I keep trying to handle this—I want to generate a clearer image but I spent way too long on the phone with adobe customer service today trying to get my photoshop license working again. 🙄

**Comment by burrelle** [comment]
It’s okay. I’m sorry I forgot the image the first time.

**Comment by mattstauffer** [comment]
Closing and adding my own image. :)

**Pull request closed without merging**
