### PR TITLE
Added ryangjchandler.co.uk

### PR DESCRIPTION
**Pull request by ryangjchandler**
Adds [ryangjchandler.co.uk](https://ryangjchandler.co.uk) to sites list

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks! Can you make the image 380x210?

**Comment by ryangjchandler** [comment]
> Thanks! Can you make the image 380x210?

Sure, didn't see that part :)

**Comment by ryangjchandler** [comment]
All done :)

**Comment by mattstauffer** [comment]
Thanks Ryan!

**Pull request merged**
